language: node_js
node_js:
  - 10.8.0

services:
  - mysql
  - redis-server

before_script:
  - yarn install
  - mysql -e 'CREATE DATABASE swavy_tees_test;'

script:
  - yarn test
  
after_success:
  - npx codecov
