language: node_js
node_js:
  - node

services:
  - mysql

before_script:
  - yarn install
  - sleep 15
  - mysql -e 'CREATE DATABASE swavy_tees_test;'

script:
  - yarn test
  
after_success:
  - npx codecov
